###########################################################
# Parameters
###########################################################

parameters:
  - name: appServices
    type: object

###########################################################
# Steps
###########################################################
stages:

  - stage: 'GIT_TAG'
    displayName: Create a git tag for this version
    jobs:
      - ${{ each service in parameters.appServices }}:
        - job: SAY_HELLO_${{ upper(service.applictionServiceID) }}
          displayName: Say Hello ${{ upper(service.applictionServiceID) }}

          #variables:
          #  - releaseVersion: 0.0.1

          steps:
            - checkout: self
              persistCredentials: true
              
            - script: echo '$(Build.BuildNumber)'
              displayName: Output Some build number  

            # - script: echo '$(Rev:r)'
            #   displayName: Rev rrrrrrr

            - script: |
                git config --global user.email "cggaldes@gmail.com"
                git config --global user.name "Christopher Galdes"
              displayName: setup git
              
            - script: |
                echo "Hello There :wave"
              displayName: smile and wave

            - script: |
                git tag ${{ service.releaseVersion }}
                git push origin ${{ service.releaseVersion }}
              displayName: git tag for ${{ service.applicationServiceID }}
